# Generated by Django 6.0.2 on 2026-03-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentstaydetails',
            name='bhk',
        ),
    ]
