# Generated by Django 6.0.2 on 2026-03-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0002_remove_apartmentstaydetails_bhk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('identityType', models.CharField(choices=[('Aadhar', 'Aadhar'), ('PAN', 'PAN'), ('Other', 'Other')], max_length=30)),
                ('identityImage', models.ImageField(upload_to='identity_proofs/')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
