# Generated by Django 6.0.2 on 2026-03-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0003_tenent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelfloorroom',
            old_name='sharing',
            new_name='beds',
        ),
        migrations.RenameField(
            model_name='hostelfloorroom',
            old_name='floor',
            new_name='floorNo',
        ),
        migrations.AlterUniqueTogether(
            name='hostelfloorroom',
            unique_together={('hostel', 'floorNo', 'roomNo')},
        ),
    ]
