# Generated by Django 6.0.2 on 2026-03-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0004_rename_sharing_hostelfloorroom_beds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelfloorroom',
            old_name='floorNo',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='hostelfloorroom',
            old_name='beds',
            new_name='sharing',
        ),
        migrations.AlterUniqueTogether(
            name='hostelfloorroom',
            unique_together={('hostel', 'floor', 'roomNo')},
        ),
    ]
