# Generated by Django 6.0.2 on 2026-03-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0005_rename_floorno_hostelfloorroom_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('bed', models.IntegerField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
                ('idUri', models.ImageField(blank=True, null=True, upload_to='identity_proofs/')),
            ],
        ),
    ]
